#!/bin/bash
set -e

echo "=== Hermes on Render (with DeepSeek proxy) — starting ==="

# Create data directories
mkdir -p /data/.hermes

# -------------------------------
# 1. Health-check HTTP server (background)
#    Render pings this on $PORT to know the service is alive
# -------------------------------
python3 -c "
from http.server import HTTPServer, BaseHTTPRequestHandler
import os

class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-Type', 'text/plain')
        self.end_headers()
        self.wfile.write(b'ok')
    def log_message(self, format, *args):
        pass

port = int(os.environ.get('PORT', 10000))
print(f'[health] listening on :{port}', flush=True)
HTTPServer(('0.0.0.0', port), HealthHandler).serve_forever()
" &
HEALTH_PID=$!
echo "[health] PID: $HEALTH_PID"

# -------------------------------
# 2. Start the DeepSeek proxy (background)
#    Hermes connects to localhost:8000/v1, proxy forwards to DeepSeek API
# -------------------------------
echo "[proxy] starting DeepSeek proxy on :8000..."
cd /app/deepseek-proxy
python3 main.py &
PROXY_PID=$!
echo "[proxy] PID: $PROXY_PID"

# Wait for proxy to be ready
for i in $(seq 1 30); do
    if curl -s http://localhost:8000/v1/models > /dev/null 2>&1; then
        echo "[proxy] ready after ${i}s"
        break
    fi
    sleep 1
done

# -------------------------------
# 3. Write Hermes config — points to local proxy
# -------------------------------
cat > /data/.hermes/config.yaml << 'HERMESCONF'
# Auto-generated by start.sh
model:
  provider: custom
  base_url: http://localhost:8000/v1
  default: deepseek-reasoner
  api_mode: chat_completions

gateway:
  enabled: true
  platforms:
    - telegram

approvals:
  mode: off
HERMESCONF

# Write .env with Telegram token
cat > /data/.hermes/.env << ENVEOF
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
ENVEOF

# -------------------------------
# 4. Run Hermes gateway
# -------------------------------
echo "[hermes] starting gateway..."
exec hermes gateway run
