#!/bin/bash
set -e

echo "=== Hermes on Render — starting ==="

# Create Hermes config directory if not exists
mkdir -p /data/.hermes

# -------------------------------
# 1. Health-check HTTP server (background)
#    Keeps Render's health check happy on $PORT
# -------------------------------
python3 -c "
from http.server import HTTPServer, BaseHTTPRequestHandler
import os, sys

class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-Type', 'text/plain')
        self.end_headers()
        self.wfile.write(b'ok')
    def log_message(self, format, *args):
        pass  # silence access logs

port = int(os.environ.get('PORT', 10000))
print(f'[health] listening on :{port}', flush=True)
HTTPServer(('0.0.0.0', port), HealthHandler).serve_forever()
" &
HEALTH_PID=$!
echo "[health] PID: $HEALTH_PID"

# -------------------------------
# 2. Write Hermes config from env vars
#    Render injects env vars, we map them to config.yaml
# -------------------------------
cat > /data/.hermes/config.yaml << 'HERMESCONF'
# Auto-generated by start.sh — edit env vars on Render dashboard, not this file
model:
  provider: custom
  base_url: ${LLM_BASE_URL}
  default: ${LLM_MODEL}
  api_mode: chat_completions

gateway:
  enabled: true
  platforms:
    - telegram

# Disable approval prompts (headless deployment)
approvals:
  mode: off
HERMESCONF

# Substitute env vars in the config
envsubst < /data/.hermes/config.yaml > /tmp/config.yaml.tmp
mv /tmp/config.yaml.tmp /data/.hermes/config.yaml

# Write .env with secrets (only needed if your proxy requires auth)
cat > /data/.hermes/.env << ENVEOF
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
ENVEOF

# -------------------------------
# 3. Run Hermes gateway
# -------------------------------
echo "[hermes] starting gateway..."
exec hermes gateway run
